BASE_URL: http://backend:8000/api
UNKNOWN_THUMBNAIL: https://i.imgur.com/jgSzqns.png
LEADERBOARD_TOP_N: 30
TTR_ICON: https://i.imgur.com/dRbZlGH.png
TTR_COLOR: 5793266
TTCC_ICON: https://i.imgur.com/5My7E8U.png
TTCC_COLOR: 10038562
OVERALL_ICON: https://i.imgur.com/kEFU1YQ.png
OVERALL_COLOR: 16776960
WELCOME_CHANNEL: 1257178370408583288
GUILD: 1254667676630913044
AUTHORIZED_ROLE: basic rights
