services:
  api:
    build:
      context: api/
    ports:
      - "9001:8000"
    depends_on:
      - backend

  bot:
    build:
      context: bot/
    depends_on:
      - backend

  backend:
    build:
      context: backend/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local