BASE_URL: http://backend:8000/api
UNKNOWN_THUMBNAIL: https://i.imgur.com/jgSzqns.png
WELCOME_CHANNEL: 1257178370408583288
GUILD: 1254667676630913044
AUTHORIZED_ROLE: basic rights
TOKEN: MTI1NDY2NzUyMjMzMTExNTYwMQ.GbxCXq._Dhwg0c_jrh1LWiMKCVHSKziit-f0OoLMzRJfU