BASE_URL: http://backend:8000/api
UNKNOWN_THUMBNAIL: https://i.imgur.com/jgSzqns.png
LEADERBOARD_TOP_N: 20
TTR_ICON: https://i.imgur.com/dRbZlGH.png
TTR_COLOR: 5793266
TTCC_ICON: https://i.imgur.com/5My7E8U.png
TTCC_COLOR: 10038562
OVERALL_ICON: https://i.imgur.com/kEFU1YQ.png
OVERALL_COLOR: 16776960
RATE_LIMIT_MESSAGE: 10
RATE_LIMIT_GLOBAL: 0.5
RECORD_CHANNELS: [['ttr', 'vp'], ['ttr', 'cfo'], ['ttr', 'cj'], ['ttr', 'ceo'], ['ttr', 'activities'], ['ttr', 'field-office'], ['ttr', 'factory'], ['ttr', 'mint'], ['ttr', 'office'], ['ttr', 'cog-golf-course']]
LEADERBOARDS: ['ttr', 'ttcc', 'overall']
PERSONAL_LEADERBOARD_SIZE: 5
